export enum Emotion {
    neutral = 'neutral',
    approval = 'approval', // admiration, amusement
    anger = 'anger',
    confusion = 'confusion',
    desire = 'desire',
    disappointment = 'disappointment', // annoyance, disapproval
    disgust = 'disgust',
    embarrassment = 'embarrassment',
    fear = 'fear', // surprised (unpleasant)
    grief = 'grief',
    guilt = 'guilt', // remorse
    joy = 'joy',
    kindness = 'kindness', // caring, gratitude
    love = 'love',
    nervousness = 'nervousness',
    pride = 'pride',
    sadness = 'sadness',
    wonder = 'wonder', // realization, curiosity, optimism, excitement, surprised (pleasant)
}

export const EMOTION_SYNONYMS: {[key: string]: Emotion} = {
    calm: Emotion.neutral,
    content: Emotion.approval,
    amusement: Emotion.approval,
    admiration: Emotion.approval,
    happy: Emotion.joy,
    pleased: Emotion.approval,
    angry: Emotion.anger,
    furious: Emotion.anger,
    fury: Emotion.anger,
    confused: Emotion.confusion,
    puzzled: Emotion.confusion,
    seductive: Emotion.desire,
    sexy: Emotion.desire,
    annoyed: Emotion.disappointment,
    disgusted: Emotion.disgust,
    embarrassed: Emotion.embarrassment,
    shocked: Emotion.fear,
    terrified: Emotion.fear,
    sad: Emotion.sadness,
    upset: Emotion.sadness,
    remorseful: Emotion.guilt,
    grateful: Emotion.kindness,
    caring: Emotion.kindness,
    lovestruck: Emotion.love,
    anxious: Emotion.nervousness,
    uncertain: Emotion.nervousness,
    proud: Emotion.pride,
    curious: Emotion.wonder,
    intrigued: Emotion.wonder,
    excited: Emotion.wonder,
    optimistic: Emotion.wonder,
    surprised: Emotion.wonder,
    realization: Emotion.wonder,
    curiosity: Emotion.wonder,
    sickened: Emotion.disgust,
    grossed_out: Emotion.disgust,
    sick: Emotion.disgust,
    depressed: Emotion.grief,
    sobbing: Emotion.grief,
    repentant: Emotion.guilt,
    remorse: Emotion.guilt,
    baffled: Emotion.confusion,
    stunned: Emotion.confusion,
    appreciative: Emotion.approval,
    excitement: Emotion.wonder,
    happiness: Emotion.joy,
    joyfulness: Emotion.joy,
    thrilled: Emotion.joy,
    placid: Emotion.neutral,
    serene: Emotion.neutral,
    tranquil: Emotion.neutral,
    stoic: Emotion.neutral,
    contented: Emotion.approval,
    delighted: Emotion.joy,
    elated: Emotion.joy,
    jubilant: Emotion.joy,
    enraged: Emotion.anger,
    livid: Emotion.anger,
    wrathful: Emotion.anger,
    confounded: Emotion.confusion,
    perplexed: Emotion.confusion,
    desirous: Emotion.desire,
    longing: Emotion.desire,
    dismayed: Emotion.disappointment,
    appalled: Emotion.disgust,
    horrified: Emotion.fear,
    thankful: Emotion.kindness,
    sweet: Emotion.kindness,
    affectionate: Emotion.love,
    flirty: Emotion.love,
    jittery: Emotion.nervousness,
    uneasy: Emotion.nervousness,
    elation: Emotion.wonder,
    haughty: Emotion.pride,
    worry: Emotion.nervousness,
    distress: Emotion.sadness,
    boredom: Emotion.neutral,
    bliss: Emotion.joy,
    ecstacy: Emotion.joy,
    suspicious: Emotion.disappointment,
    suspicion: Emotion.disappointment,
    playfulness: Emotion.joy,
    playful: Emotion.joy,
    fun: Emotion.joy,
    delight: Emotion.joy,
    appreciation: Emotion.approval,
    tenderness: Emotion.kindness,
    care: Emotion.kindness,
}

export const EMOTION_PROMPTS: {[emotion in Emotion]?: string} = {
    neutral: 'calm expression',
    approval: 'approving, appreciative, pleased expression',
    anger: 'enraged, angry expression',
    confusion: 'stunned, baffled, confused expression',
    desire: 'sexy, alluring, seductive expression',
    disappointment: 'unhappy, mildly dismayed expression',
    disgust: 'disgusted, grossed-out expression',
    embarrassment: 'embarrassed, sheepish expression',
    fear: 'shocked, terrified expression',
    grief: 'depressed, sobbing expression',
    guilt: 'remorseful, repentant expression',
    joy: 'happy, smiling',
    kindness: 'kind, caring, grateful expression',
    love: 'adorable, grinning, lovestruck expression',
    nervousness: 'anxious, uncertain expression',
    pride: 'proud, haughty, puffed up expression',
    sadness: 'sad, upset expression',
    wonder: 'excitedly curious, intrigued expression',
}

export type EmotionPack = {[key: string]: string};
